version: '1'

services:
  postgresql:
    image: crypto-pro
    container_name: crypto-pro
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DATABASE=crypto-pro
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-crypto-pro
    ports:
      - '6379-6379'
